# Generated by Django 5.0.6 on 2026-06-12 18:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('mold', 'Mold / dampness'), ('pests', 'Pests (mice, roaches, bedbugs)'), ('heat', 'No heat / inadequate heat'), ('water', 'Water / plumbing'), ('repairs', 'Repairs not done'), ('safety', 'Safety (locks, fire, structural)'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('session_hash', models.CharField(db_index=True, help_text='SHA-256 of (SECRET_KEY + session key). Raw session key is never stored.', max_length=64)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False, help_text="Hidden complaints don't appear publicly (flagged, awaiting moderation).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('flagger_session_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('resolved', 'Resolved (complaint removed)'), ('rejected', 'Rejected (complaint restored)')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(help_text="Normalized street address, e.g. '123 King St E'")),
                ('city', models.CharField(default='Hamilton', max_length=100)),
                ('postal_code_prefix', models.CharField(blank=True, help_text="First 3 characters only (FSA), e.g. 'L8N' — never the full code", max_length=3)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='core_buildi_city_9bbacb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('address', 'city'), name='uniq_building_address_city'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.building'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='core.complaint'),
        ),
        migrations.AddField(
            model_name='flaggedcomplaint',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.complaint'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['building', 'is_hidden'], name='core_compla_buildin_a96497_idx'),
        ),
        migrations.AddConstraint(
            model_name='confirmation',
            constraint=models.UniqueConstraint(fields=('complaint', 'session_hash'), name='uniq_confirmation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='flaggedcomplaint',
            constraint=models.UniqueConstraint(fields=('complaint', 'flagger_session_hash'), name='uniq_flag_per_session'),
        ),
    ]
